# Thanks to https://medium.com/swlh/beautiful-load-testing-with-k6-and-docker-compose-4454edb3a2e3
version: '3.4'
services:
  influxdb:
    image: influxdb:1.8
    platform: linux/x86_64
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=k6
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  grafana:
    image: grafana/grafana:latest

    ports:
      - '3000:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  jaeger:
    image: jaegertracing/all-in-one:latest
    platform: linux/x86_64
    ports:
      - '14250:14250'
      - '14268:14268'
      - '14269:14269'
      - '4318:4318'
      - '4317:4317'
      - '6831:6831/udp'
      - '16686:16686'
      - '16685:16685'
      - '9411:9411'
    volumes:
      - './jaeger-ui.json:/etc/jaeger/jaeger-ui.json'
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    environment:
#      - METRICS_STORAGE_TYPE=prometheus
#      - PROMETHEUS_SERVER_URL=http://172.17.0.1:9090
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
      - JAEGER_DISABLED=true
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  webapi:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      jaeger:
        condition: service_started
      influxdb:
        condition: service_started
      grafana:
        condition: service_started
      prometheus:
        condition: service_started
    platform: linux/x86_64
    ports:
      - '1234:1234'
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - K6_OUT=influxdb=http://172.17.0.1:8086/k6
    volumes:
      - ../:/workspace:cached
      - ../node_modules:/workspace/node_modules
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  prometheus-data:
